language: python

sudo: required

services:
  - docker

env:
  global:
    - LATEST_VERSION=8
  matrix:
    - DRUPAL=6 NGINX=1.10
    - DRUPAL=7 NGINX=1.10
    - DRUPAL=8 NGINX=1.10

install:
  - cd ./$DRUPAL/$NGINX
  - make

script: make test

after_success: |
  if [ "$TRAVIS_PULL_REQUEST" == "false" ] && ([ "$TRAVIS_BRANCH" == "master" ] || [ -n "$TRAVIS_TAG" ]); then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    make release

    if [ -n "$TRAVIS_TAG" ]; then
      make VERSION="$TRAVIS_TAG" release
    fi

    if [ "$VERSION" == "$LATEST_VERSION" ]; then
      make VERSION=latest release
    fi
  fi

after_failure:
  - make logs